import { Component, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '../core/auth/auth.service';
import { Attachment, Message, MessagingService } from '../core/messaging.service';
import { ApplicationService } from '../core/application/application.service';
import { CompanyService } from '../core/company/company.service';
@Component({standalone:true,imports:[CommonModule,FormsModule,DatePipe,RouterLink,MatButtonModule,MatIconModule,MatProgressSpinnerModule],template:`<main class="conversation-page"><header class="conversation-header"><a [routerLink]="backLink()" mat-button><mat-icon>arrow_back</mat-icon> {{backLabel()}}</a><div><p>Messagerie candidature</p><h1>{{conversationTitle()}}</h1></div></header><section class="conversation-card"><div *ngIf="loading()" class="conversation-loading"><mat-spinner diameter="36"></mat-spinner></div><div *ngIf="errorMessage()" class="conversation-error">{{errorMessage()}}</div><div *ngIf="!loading()&&!errorMessage()&&!messages().length" class="conversation-empty"><mat-icon>forum</mat-icon><h2>Démarrez la conversation</h2><p>Envoyez un message ou une pièce jointe.</p></div><div *ngIf="!loading()&&!errorMessage()" class="messages-list"><article *ngFor="let message of messages()" class="message" [class.mine]="message.sender_user_id===userId"><div class="message-meta">{{message.sender_user_id===userId?'Vous':message.sender_email||otherPartyLabel()}} · {{message.created_at|date:'dd/MM/yyyy HH:mm'}}</div><p *ngIf="message.body">{{message.body}}</p><a *ngIf="message.attachment_data" class="attachment" [href]="message.attachment_data" [download]="message.attachment_name"><mat-icon>{{message.attachment_mime_type?.startsWith('image/')?'image':'attach_file'}}</mat-icon>{{message.attachment_name}}</a></article></div><form class="composer" (ngSubmit)="send()"><textarea [(ngModel)]="draft" name="draft" rows="3" maxlength="1000" placeholder="Écrivez votre message..."></textarea><div class="composer-actions"><label class="attach-button"><mat-icon>attach_file</mat-icon> Joindre un fichier<input type="file" accept="image/*,.pdf,.txt,.doc,.docx,.zip" (change)="selectFile($event)" hidden></label><span *ngIf="attachment" class="selected-file">{{attachment.name}} <button type="button" (click)="clearFile()">×</button></span><button mat-flat-button color="primary" type="submit" [disabled]="sending()||(!draft.trim()&&!attachment)"><mat-icon>send</mat-icon> Envoyer</button></div></form></section></main>`,styleUrl:'./conversation.page.scss'})
export class ConversationPage {private readonly route=inject(ActivatedRoute);private readonly auth=inject(AuthService);private readonly messaging=inject(MessagingService);private readonly applications=inject(ApplicationService);private readonly companyService=inject(CompanyService);readonly loading=signal(true);readonly sending=signal(false);readonly errorMessage=signal('');readonly messages=signal<Message[]>([]);readonly backLink=signal('/my-applications');readonly backLabel=signal('Mes candidatures');readonly conversationTitle=signal('Échange avec l’entreprise');readonly otherPartyLabel=signal('Entreprise');draft='';attachment:Attachment|null=null;applicationId='';userId='';async ngOnInit(){this.applicationId=this.route.snapshot.paramMap.get('applicationId')||'';this.userId=this.auth.user()?.id||'';await this.loadContext();await this.load();}async loadContext(){if(this.auth.user()?.role!=='COMPANY')return;try{const profile=await this.companyService.getProfile(this.userId);const result=await this.applications.getApplicationById(this.applicationId,undefined,profile.company.id);const offerId=result.application.offer_id;if(offerId){this.backLink.set('/offers/'+offerId+'/applications');this.backLabel.set('Candidatures pour l’offre');}this.conversationTitle.set('Échange avec le candidat');this.otherPartyLabel.set('Candidat');}catch{this.conversationTitle.set('Échange avec le candidat');this.otherPartyLabel.set('Candidat');}}async load(){try{this.messages.set((await this.messaging.list(this.applicationId,this.userId)).messages);}catch(error){this.errorMessage.set(error instanceof Error?error.message:'Impossible de charger la conversation.');}finally{this.loading.set(false);}}selectFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>5*1024*1024){this.errorMessage.set('Le fichier ne doit pas dépasser 5 Mo.');return;}const reader=new FileReader();reader.onload=()=>{this.attachment={name:file.name,mimeType:file.type||'application/octet-stream',data:String(reader.result)};this.errorMessage.set('');};reader.readAsDataURL(file);}clearFile(){this.attachment=null;}async send(){const body=this.draft.trim();if((!body&&!this.attachment)||this.sending())return;this.sending.set(true);try{const result=await this.messaging.send(this.applicationId,this.userId,body,this.attachment||undefined);this.messages.update(items=>[...items,result.message]);this.draft='';this.attachment=null;}catch(error){this.errorMessage.set(error instanceof Error?error.message:'Impossible d’envoyer le message.');}finally{this.sending.set(false);}}}
