import { Component, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { AuthService } from '../core/auth/auth.service';
import { NotificationItem, NotificationService } from '../core/notification.service';
@Component({standalone:true,imports:[CommonModule,DatePipe,MatButtonModule,MatIconModule],template:`<main class="notifications-page"><section class="notifications-hero"><div><p class="eyebrow">Centre de suivi</p><h1>Notifications</h1><p>Retrouve les réponses des entreprises et les activités de tes candidatures.</p></div><button mat-stroked-button (click)="markAllRead()">Tout marquer comme lu</button></section><section class="notifications-list">@if (loading()) { <p class="empty">Chargement...</p> } @else if (!notifications().length) { <p class="empty">Aucune notification pour le moment.</p> } @else { @for (item of notifications(); track item.id) { <article class="notification-card" [class.unread]="!item.is_read"><div class="notification-symbol"><mat-icon>{{ item.is_read ? 'notifications_none' : 'notifications_active' }}</mat-icon></div><div><h2>{{ item.title }}</h2><p>{{ item.content }}</p><small>{{ item.created_at | date:'dd/MM/yyyy HH:mm' }}</small></div><button mat-button *ngIf="!item.is_read" (click)="markRead(item)">Marquer lu</button></article> } }</section></main>`,styles:[`.notifications-page{max-width:980px;margin:0 auto;padding:42px 24px 72px}.notifications-hero{display:flex;justify-content:space-between;gap:24px;align-items:center;padding:32px;border-radius:22px;background:#1f2933;color:#fffdf8}.eyebrow{margin:0 0 8px;color:#f4bb59;font-size:.75rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.notifications-hero h1{margin:0 0 8px}.notifications-hero p:not(.eyebrow){margin:0;color:#d7dee5}.notifications-list{display:grid;gap:14px;margin-top:22px}.notification-card{display:flex;align-items:center;gap:16px;padding:20px;border:1px solid #e4ddd0;border-radius:16px;background:#fffdf8}.notification-card.unread{border-color:#d3542b}.notification-symbol{display:grid;place-items:center;width:44px;height:44px;border-radius:14px;background:#f5f1e8;color:#d3542b}.notification-card h2{margin:0 0 5px;font-size:1rem}.notification-card p{margin:0 0 5px;color:#59636e}.notification-card small{color:#8a5a42}.notification-card button{margin-left:auto}.empty{padding:40px;text-align:center;color:#59636e}`]})
export class NotificationsPage { private readonly auth=inject(AuthService); private readonly api=inject(NotificationService); readonly loading=signal(true); readonly notifications=signal<NotificationItem[]>([]); async ngOnInit(){const userId=this.auth.user()?.id;if(!userId){this.loading.set(false);return;}try{this.notifications.set((await this.api.list(userId)).notifications);}finally{this.loading.set(false);}} async markRead(item:NotificationItem){const userId=this.auth.user()?.id;if(!userId||item.is_read)return;await this.api.markRead(item.id,userId);this.notifications.update(items=>items.map(value=>value.id===item.id?{...value,is_read:true}:value));} async markAllRead(){const userId=this.auth.user()?.id;if(!userId)return;await this.api.markAllRead(userId);this.notifications.update(items=>items.map(value=>({...value,is_read:true})));}}

