import { Injectable, BadRequestException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { PostgresService } from './postgres.service';
export interface MessageAttachment { name: string; mimeType: string; data: string; }
@Injectable()
export class MessagingService {
 constructor(private readonly db: PostgresService) {}
 private async participants(applicationId:string){const result=await this.db.query<{student_user_id:string;company_user_id:string}>(`SELECT s.user_id AS student_user_id, c.user_id AS company_user_id FROM applications a JOIN students s ON s.id=a.student_id JOIN offers o ON o.id=a.offer_id JOIN companies c ON c.id=o.company_id WHERE a.id=$1`,[applicationId]);if(!result.rows[0])throw new NotFoundException('Application not found');return result.rows[0];}
 async list(applicationId:string,userId:string){const people=await this.participants(applicationId);if(![people.student_user_id,people.company_user_id].includes(userId))throw new ForbiddenException('You are not a participant');const result=await this.db.query(`SELECT m.id,m.application_id,m.sender_user_id,m.body,m.attachment_name,m.attachment_mime_type,m.attachment_data,m.created_at,u.email AS sender_email FROM messages m JOIN users u ON u.id=m.sender_user_id WHERE m.application_id=$1 ORDER BY m.created_at ASC`,[applicationId]);return {messages:result.rows};}
 async send(applicationId:string,senderUserId:string,body:string,attachment?:MessageAttachment){const content=(body||'').trim();if(!content&&!attachment)throw new BadRequestException('Message body or attachment is required');if(attachment){if(!attachment.name||!attachment.mimeType||!attachment.data)throw new BadRequestException('Invalid attachment');if(attachment.data.length>7000000)throw new BadRequestException('Attachment is too large (5 MB maximum)');const allowed=attachment.mimeType.startsWith('image/')||['application/pdf','text/plain','application/zip','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'].includes(attachment.mimeType);if(!allowed)throw new BadRequestException('File type is not supported');}const people=await this.participants(applicationId);if(![people.student_user_id,people.company_user_id].includes(senderUserId))throw new ForbiddenException('You are not a participant');const receiverUserId=people.student_user_id===senderUserId?people.company_user_id:people.student_user_id;const result=await this.db.query(`INSERT INTO messages(application_id,sender_user_id,body,attachment_name,attachment_mime_type,attachment_data) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,application_id,sender_user_id,body,attachment_name,attachment_mime_type,attachment_data,created_at`,[applicationId,senderUserId,content,attachment?.name||null,attachment?.mimeType||null,attachment?.data||null]);await this.db.query(`INSERT INTO notifications(user_id,title,content) VALUES($1,$2,$3)`,[receiverUserId,attachment?'Nouvelle pièce jointe':'Nouveau message',(content||attachment?.name||'').slice(0,160)]);return {message:result.rows[0]};}
}
